FROM lscr.io/linuxserver/foldingathome:latest

# Home Assistant läuft standardmäßig als Root, die PUID/PGID Optionen in der config.yaml 
# stellen sicher, dass das LinuxServer Image die Berechtigungen korrekt setzt.
